server:
  port: 8088
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

jedis:
  host: 127.0.0.1
  port: 6379
  max-total: 20
  max-idle: 10
  min-idle: 5
  test-on-borrow: true
  test-on-return: false